alias vim="nvim"
alias py="python3"
alias la="ls -a"
alias glog="git log --all --oneline --pretty=format:'%C(auto)%h%C(blue) %<|(19)%as%C(auto)%d %s' --graph"
alias ll="ls -lhk"
alias mv="mv -i"
alias mkdir="mkdir -p"
alias cp="cp -r"
alias df="df -h"
alias c="clear"
alias t="tmux"
alias ta="tmux a"
alias lg="lazygit"
