default_variable_name_type = "Unique"
default_clock_highlight_type = "Line"
snap_distance = 6
theme = ""
undo_stack_size = 50

[default_time_format]
format = "No"
show_space = true
show_unit = true

[layout]
show_hierarchy = true
show_menu = true
show_toolbar = true
show_ticks = true
show_tooltip = true
show_scope_tooltip = false
show_overview = true
show_statusbar = true
show_variable_indices = true
show_variable_direction = true
show_default_timeline = true
show_empty_scopes = false
show_parameters_in_scopes = true
window_width = 1920
window_height = 1080
align_names_right = false
hierarchy_style = "Separate"
waveforms_text_size = 11.0
waveforms_line_height = 16.0
transactions_line_height = 30.0
zoom_factors = [0.5, 0.75, 0.9, 1.0, 1.1, 1.25, 1.5, 2.0, 2.5]
default_zoom_factor = 2.0
highlight_focused = false
move_focus_on_inserted_marker = true
fill_high_values = true

[gesture]
size = 300
deadzone = 20
background_radius = 1.35
background_gamma = 0.75

[gesture.mapping]
north = "Cancel"
south = "Cancel"
west = "ZoomIn"
east = "ZoomIn"
northeast = "ZoomOut"
northwest = "ZoomToFit"
southeast = "GoToEnd"
southwest = "GoToStart"

[behavior]
keep_during_reload = true
arrow_key_bindings = "Edge"

[wcp]
autostart = false
address = "127.0.0.1:54321"
