hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("swaync")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --watch cliphist store -max-items 200")
    hl.exec_cmd("fcitx5 --replace -d")
    hl.exec_cmd("~/dotfiles/hypr/scripts/init-wallpaper-engine.sh")
    hl.exec_cmd("clash-verge")
end)
