monitorv2 {
    output = eDP-1
    mode = preferred
    position = 0x0
    scale = 1
}

monitorv2 {
    output = HDMI-A-1
    mode = preferred
    position = 2560x0
    scale = 1
    transform = 1
}

monitorv2 {
    output = DP-1
    mode = preferred
    position = 4720x0
    scale = 1
}
