layout=reduced
showonpause=yes
timetotal=yes
timems=no
visibility=auto
boxalpha=80
idlescreen=yes
deadzone=200
showwindowed=yes
showfullscreen=no
scalewindowed=1
scalefullscreen=1
scaleforcedwindow=2
vidscale=yes
hidetimeout=500
fadeduration=200
minmousemove=3
iamaprogrammer=no
font=mpv-osd-symbols
seekrange=yes
seekrangealpha=128
seekbarkeyframes=yes
title=${media-title}
windowcontrols=auto
volumecontrol=yes
processvolume=yes
language=chs
